### ISSUE TITLE
Looking for new maintainers / possible project deprecation

### ISSUE THREAD

**Issue by utrack** [utrack/clay#101]
Putting up this issue to ping everyone who watches this repo.

See the announcement here: https://github.com/utrack/clay/commit/ff09f4042425958c7f3a4ab7bd088deae30e3850

**Comment by bullgare** [comment]
Hello, @utrack !
It is very sad.
At this exact moment, I don't have enough time, but I'd love to participate a bit later.
Unless someone else would want to own it before.
Anyway, please do not deprecate it.
