### ISSUE TITLE
Implement Validator interface

### ISSUE THREAD

**Issue by eaglemoor** [utrack/clay#44]
We need add Validator interface for Request struct. When request struct fetch data from request and if it implement Validator interface, we can validate data in request and return error before handler.

```
type Validator interface {
	Valid() bool
}
```

**Comment by utrack** [comment]
You can use middleware for that - it has access to the message struct.
Set it up via [desc.Apply()](https://github.com/utrack/clay/blob/master/doc/example/pb/sum.pb.goclay.go#L67), passing [transport.WithUnaryServerInterceptor()](https://github.com/utrack/clay/blob/master/transport/options.go#L15)

**Comment by eaglemoor** [comment]
desc.Apply & transport.WithUnaryServerInterceptor() supported only for grps, and don't support for rest.
