### ISSUE TITLE
Apply a configurable swagger option

### ISSUE THREAD

**Issue by NOMORECOFFEE** [utrack/clay#68]
I think these [options](https://github.com/utrack/clay/blob/v2.4.0-ozon/cmd/protoc-gen-goclay/genhandler/tpl_servicedesc.go#L43) (d.opts.SwaggerDefaultOpts) should be present in this [condition](https://github.com/utrack/clay/blob/v2.4.0-ozon/cmd/protoc-gen-goclay/genhandler/tpl_servicedesc.go#L36)

If a service is`ConfigurableServiceDesc`, we can append additional swagger [option](https://github.com/utrack/clay/blob/master/transport/options.go#L20-L22) but not check it

**Comment by utrack** [comment]
What do you mean by checking them? What should we check for @ that if?

**Comment by NOMORECOFFEE** [comment]
```
if len(options) > 0 || len(d.opts.SwaggerDefaultOpts) {
...
}
```

**Comment by NOMORECOFFEE** [comment]
```
var s interface{ConfigurableServiceDesc; ServiceDesc} = ...
s.Apply(WithSwaggerOptions(removeSwaggeSpec)) // or change Version
spec := s. SwaggerDef() // wait changes
```

**Comment by utrack** [comment]
Thanks!
