### ISSUE TITLE
Unmarshal panic

### ISSUE THREAD

**Issue by NOMORECOFFEE** [utrack/clay#70]
https://github.com/utrack/clay/blob/master/transport/httpruntime/mjson.go#L41
it's not correct logical operator `&&` for `v = v.Elem()`  invoked [here](https://github.com/utrack/clay/blob/master/transport/httpruntime/mjson.go#L51)

https://golang.org/pkg/reflect/#Value.Elem
It panics if v's Kind is not Interface **OR** Ptr.

I think it should be `||`

**Comment by utrack** [comment]
Why? Elem panics if it's not an interface or a pointer; we break the loop if v is neither an interface nor a pointer. Looks right to me.

**Comment by NOMORECOFFEE** [comment]
@utrack you are right. Sorry for issue
