### ISSUE TITLE
template.go:1056] no message found: Error

### ISSUE THREAD

**Issue by bullgare** [utrack/clay#81]
From time to time while using goclay I see these messages in shell:
```
template.go:1056] no message found: Error
```
In this situation an extra code for swagger is being generated:
```
"default": {
  "description": "An unexpected error response",
  "schema": {
    "$ref": "#/definitions/"
  }
}
```

Which leads to issues on swagger-ui with outputting resources.

**As far as I understood, it happens when `.pb.goclay.go` is already exist.**

**Comment by utrack** [comment]
The problem can be caused by new grpc-gateway's genswagger; I'll get on it soon.

**Comment by bullgare** [comment]
Thanks!
Will be waiting patiently :)
