### ISSUE TITLE
Version 3

### ISSUE THREAD

**Issue by utrack** [utrack/clay#97]
With the protoc-gen-go v1.20.0+ and new gRPC generator breaking compatibility (see https://github.com/grpc/grpc-go/pull/3828), it seems that a big refactoring process will be needed (and frankly, current code calls for it).

This is a good chance to implement some things in a better way and throw away some others: for example, tricky output rules pre-`--module` flag.

This is an umbrella issue that will collect everything that will go to v3.0.0.

**Comment by bullgare** [comment]
If you need any help with that (like writing tests or code review) - feel free to ask.
Hope I will have time at nights :)

**Comment by wish-master** [comment]
+1 to @bullgare, @utrack I'm in

**Comment by utrack** [comment]
Thank you, guys!
